[Appearance]
style=kvantum
custom_palette=true
color_scheme_path=/home/musashi/.config/qt6ct/colors/vagabond.conf
icon_theme=Papirus-Dark
standard_dialogs=default

[Fonts]
fixed="Maple Mono NF,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
general="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"

[Interface]
cursor_flash_time=1000

[Interface]
stylesheets=/home/musashi/.config/qt6ct/qss/dolphin-fix.qss
