#!/usr/bin/env bash
set -euo pipefail

TS=$(date +%Y%m%d-%H%M%S)

echo "==> musahi1 — deploying configs"
echo

backup_if_exists() {
    local target="$1"
    if [ -e "$target" ] && [ "$(ls -A "$target" 2>/dev/null)" ]; then
        cp -r "$target" "${target}.backup.${TS}"
        echo "==> Backed up existing $target -> ${target}.backup.${TS}"
    fi
}

mkdir -p ~/.config/hypr/conf.d ~/.config/waybar ~/.config/rofi ~/.config/kitty \
         ~/.config/swaync ~/.config/qt6ct/colors ~/.config/qt6ct/qss \
         ~/.config/Kvantum ~/.config/fontconfig

backup_if_exists ~/.config/hypr
backup_if_exists ~/.config/waybar
backup_if_exists ~/.config/rofi
backup_if_exists ~/.config/kitty
backup_if_exists ~/.config/swaync

echo "==> Copying configs..."
cp -r config/hypr/* ~/.config/hypr/
cp -r config/waybar/* ~/.config/waybar/
cp -r config/rofi/* ~/.config/rofi/
cp -r config/kitty/* ~/.config/kitty/
cp -r config/swaync/* ~/.config/swaync/
cp config/qt6ct/qt6ct.conf ~/.config/qt6ct/
cp config/qt6ct/colors/vagabond.conf ~/.config/qt6ct/colors/
cp config/qt6ct/qss/dolphin-fix.qss ~/.config/qt6ct/qss/
cp config/kvantum/kvantum.kvconfig ~/.config/Kvantum/
cp config/kdeglobals ~/.config/kdeglobals
cp config/fontconfig/fonts.conf ~/.config/fontconfig/

# Guard against Hyprland's autogenerated hyprland.lua silently overriding
# our hyprland.conf (Hyprland loads .lua over .conf if both exist).
if [ -f ~/.config/hypr/hyprland.lua ]; then
    echo "==> Removing autogenerated hyprland.lua (would override our .conf)"
    rm ~/.config/hypr/hyprland.lua
fi

fc-cache -f > /dev/null 2>&1 || true

echo
echo "==> Done."
echo "Restart Hyprland (SUPER+M then relog, or reboot) to fully apply changes."
echo "A plain 'hyprctl reload' is NOT enough for a first-time install —"
echo "the .lua vs .conf check only happens at Hyprland startup."
