background            #0D0B14
foreground             #EDE6F5
cursor                 #E8703A
cursor_text_color      #0D0B14
selection_background   #4B3F72
selection_foreground   #EDE6F5
url_color               #6E5A99
active_tab_background   #4B3F72
active_tab_foreground   #EDE6F5
inactive_tab_background #1B1730
inactive_tab_foreground #A79BC2
color0  #1B1730
color1  #E8703A
color2  #6E5A99
color3  #C2A15A
color4  #4B3F72
color5  #8C6FA9
color6  #A98CA6
color7  #A79BC2
color8  #2E2650
color9  #F0916A
color10 #8C7FCC
color11 #D4B878
color12 #6E5A99
color13 #A98CA6
color14 #C2A9D9
color15 #EDE6F5
