input {
    kb_layout = us,ara
    kb_options = grp:alt_shift_toggle
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0
}

gestures {
    # Trackpad gesture: 3-finger horizontal swipe = switch workspace
}

# Trackpad gesture: 3-finger horizontal swipe = switch workspace
gesture = 3, horizontal, workspace
