layerrule = blur 1, match:namespace waybar
layerrule = xray 1, match:namespace waybar
layerrule = blur 1, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi
layerrule = blur 1, match:namespace swaync-control-center
layerrule = blur 1, match:namespace swaync-notification-window
layerrule = xray 1, match:namespace swaync-control-center
layerrule = xray 1, match:namespace swaync-notification-window
