layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blur, rofi
layerrule = ignorealpha 0.5, rofi
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
