windowrule = float 1, match:class ^(pavucontrol)$
windowrule = float 1, match:class ^(nm-connection-editor)$
windowrule = float 1, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float 1, match:class ^(swappy)$
windowrule = float 1, match:title ^(Open File)$
windowrule = center 1, match:title ^(Open File)$
windowrule = no_blur 1, match:class ^(hyprlock)$
windowrule = float 1, match:class ^(swaync-control-center)$
