-- musahi1
-- Main Hyprland configuration

local hl = require("hyprland")

require("variables")
require("appearance")
require("animations")
require("input")
require("monitors")
require("binds")
require("startup")

hl.config({
    autogenerated = false
})
