-- musahi1
-- Main Hyprland configuration

local hl = require("hyprland")

require("variables")

require("environment")
require("monitors")
require("input")

require("appearance")
require("animations")

require("windowrules")
require("binds")
require("startup")

hl.config({
    autogenerated = false
})
