background            #14180F
foreground             #F5F0DC
cursor                 #C9D97A
cursor_text_color      #14180F
selection_background   #5E7C3D
selection_foreground   #F5F0DC
url_color               #8FA662
active_tab_background   #5E7C3D
active_tab_foreground   #F5F0DC
inactive_tab_background #202B18
inactive_tab_foreground #B9C79A
color0  #202B18
color1  #B57B54
color2  #8FA662
color3  #C2B75A
color4  #5B7A6C
color5  #8C8A6F
color6  #A8C494
color7  #B9C79A
color8  #4A5C3A
color9  #D99A6A
color10 #C9D97A
color11 #E4D878
color12 #7BB8A0
color13 #A9A98C
color14 #BFE8AC
color15 #F5F0DC
