font_family      Maple Mono NF
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

background_opacity 0.90
confirm_os_window_close 0

cursor_shape beam
cursor_blink_interval 0.5

enable_audio_bell no

window_padding_width 10

tab_bar_style hidden

foreground #F2EAD3
background #101511

selection_foreground #101511
selection_background #A8B58A

cursor #A8B58A

color0  #101511
color1  #8C4F4F
color2  #6D8B5B
color3  #B59B5A
color4  #6A8CAA
color5  #8C6A9A
color6  #5F8B83
color7  #E8DFC8

color8  #3B4A3D
color9  #B35D5D
color10 #88B06A
color11 #D4B96E
color12 #7CA8D6
color13 #A07BC0
color14 #73A89C
color15 #F5F0E1
